# Minikube 특화 패치를 적용합니다.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonAnnotations:
  researchex.io/platform: minikube
patchesStrategicMerge:
  - patches/storageclass-postgres.yaml
  - patches/storageclass-kafka.yaml
  - patches/storageclass-zookeeper.yaml
  - patches/ingress-host.yaml
